name: Email Step Demo

on:
  push:
    branches: [ main ]   # Trigger on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f3002868@ds.study.iitm.ac.in
        run: echo "Hello, world!"
