name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-40f0a16

      - name: prime-cache-40f0a16
        run: echo "Cache step result: ${{ steps.cache.outputs.cache-hit }}"
